
spring:
  application:
    name: item-service
    
#server:
  #port: 8003
  

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
      
--- 
spring:
   profiles: item1
server:
  port: 8003
  
--- 
spring:
   profiles: item2
server:
  port: 8002 