
spring:
  application:
    name: zuul
    
server:
  port: 300111111
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
fxhfdhfdsghfxghfghcghfghfgshfgshfgh
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
                      
